import { Inter } from "next/font/google";
import "../globals.css";
import React from "react";
import { BrowserRouter, Switch, Route } from "react-router-dom";
//import { MeetProvider } from ".../context/MeetContext";
import Meeting from "./[key]/page";
import Home from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body className={inter.className}>
      <MeetProvider>
      <BrowserRouter>
        <Switch>
          <Route path="/" component={Home} exact />
          <Route path="/:key" component={Meeting} exact />
          {/* <Route path="/thank-you" component={ThankYou} /> */}
        </Switch>
      </BrowserRouter>
      </MeetProvider>
      </body>
    </html>
  );
}
